[application]

name = "pwgen"
out_dir = "target/dist"
asset_dir = "public"

[web.app]

# HTML title tag content
title = "pwgen"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "org.omusubi.aki.nt.pwgen"
publisher = "aki.akaguma"

icon = [
  "assets/app.png",
  "assets/favicon.ico"
]

copyright = "Copyright 2026 aki.akaguma"
category = "Utility"
short_description = "passworg generator"
long_description = "Password generator"
deb = { section = "AAA-desktop", priority = "optional", files = {} }
