# This is a template parameter used by guic (guidon cli).
[variables]
project_name = "pwgen"
app_name = "PwgenWva"
package_id = "org.omusubi.aki.wva.pwgen"
version_code = "1"
version_name = "0.1"
#
compile_sdk_version = "36"
target_sdk_version = "36"
min_sdk_version = "28"
